# Generated by Django 4.1.7 on 2023-06-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0002_alter_eaduser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaduser',
            name='is_ca',
            field=models.BooleanField(default=False, verbose_name='campus ambassador'),
        ),
    ]
