# Generated by Django 4.2.2 on 2023-07-12 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ead", "0003_eaduser_is_ca"),
    ]

    operations = [
        migrations.CreateModel(
            name="EADNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name="eaduser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="ead/profiles/"),
        ),
    ]
