# Generated by Django 4.2.2 on 2023-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ead", "0005_eaduser_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="eaduser",
            name="referred_by",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
