# Generated by Django 4.2.2 on 2023-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ead", "0006_eaduser_referred_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eaduser",
            name="referred_by",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
