# Generated by Django 4.1.7 on 2023-06-27 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSMUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('lsm_city', models.CharField(choices=[('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('kochi', 'Kochi')], max_length=255)),
                ('startup', models.BooleanField(default=False, verbose_name='have startup')),
                ('sector', models.CharField(choices=[('agritech', 'Agri Tech'), ('fintech', 'Fin Tech'), ('other', 'other')], max_length=255)),
            ],
        ),
    ]
