# Generated by Django 4.1.7 on 2023-06-28 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingPage', '0002_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresarioUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_startup_name', models.CharField(max_length=255)),
                ('team_leader', models.CharField(max_length=255)),
                ('team_leader_linkedin', models.URLField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('other', 'Prefer not to say')], max_length=255)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_contact', models.IntegerField()),
                ('cofounder', models.CharField(max_length=255, null=True)),
                ('cofounder_email', models.EmailField(max_length=254, null=True)),
                ('cofounder_contact', models.IntegerField(null=True)),
            ],
        ),
    ]
