# Generated by Django 4.1.7 on 2023-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresariouser',
            name='cofounder_contact',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresariouser',
            name='primary_contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
