# Generated by Django 4.2.2 on 2023-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresario", "0003_empresarioquestionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresariouser",
            name="questionare_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
