# Generated by Django 4.2.2 on 2023-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresario", "0007_alter_empresariouser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresariouser",
            name="cofounder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresariouser",
            name="cofounder_contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="empresariouser",
            name="cofounder_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
