# Generated by Django 4.2.2 on 2023-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresario", "0008_alter_empresariouser_cofounder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresarioquestionnaire",
            name="miscellaneous",
            field=models.CharField(default="0", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresarioquestionnaire",
            name="pitch_deck",
            field=models.FileField(blank=True, null=True, upload_to="pitchdeck/"),
        ),
        migrations.AddField(
            model_name="empresarioquestionnaire",
            name="supporting_docs",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="empresarioquestionnaire",
            name="website_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresariouser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
