# Generated by Django 4.2.2 on 2023-07-04 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresario", "0010_empresarioquestionnaire_reach"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresarioNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=255)),
                ("date", models.DateTimeField(blank=True, default=datetime.date.today)),
            ],
        ),
    ]
