# Generated by Django 4.2.2 on 2023-07-04 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresario", "0011_empresarionotice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresarionotice",
            name="date",
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
