# Generated by Django 4.2.2 on 2023-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresario", "0012_alter_empresarionotice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresariouser",
            name="pitch_deck",
            field=models.ImageField(
                blank=True, null=True, upload_to="empresario/pitchdeck/"
            ),
        ),
        migrations.AlterField(
            model_name="empresariouser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="empresario/profiles/"
            ),
        ),
    ]
