# Generated by Django 4.1.7 on 2023-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empresario',
            field=models.BooleanField(blank=True, default=False, verbose_name='registered for empresario'),
        ),
    ]
